[package]
name = "dev-env-rust-arch-linux-vscode"
version = "0.4.0"
authors = ["Lukasz Orlowski <lukasz@orlowski.io"]
edition = "2024"

[dependencies]
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[dev-dependencies]
tracing-test = "0.2.5"