name: Rust dev environment verification

on:
  push:
    branches:
      - master
      - ci/*
    tags:
      # You may want to add axiomatic labels like alpha, beta, rc, et al.
      - v[0-9]+.[0-9]+.[0-9]+

  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Run checks on formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Check TOML
        uses: dprint/check@v2.2

      - name: Lint code
        run: make lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Build in container
        uses: docker/build-push-action@v6
        with:
          tags: test-build:latest
          build-args: |
            TARGET=${{ matrix.target }}
